--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image9')
--ALTER TABLE dbo.[vehicleimages] ADD image9 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image10')
--ALTER TABLE dbo.[vehicleimages] ADD image10 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image11')
--ALTER TABLE dbo.[vehicleimages] ADD image11 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image12')
--ALTER TABLE dbo.[vehicleimages] ADD image12 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image13')
--ALTER TABLE dbo.[vehicleimages] ADD image13 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image14')
--ALTER TABLE dbo.[vehicleimages] ADD image14 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image15')
--ALTER TABLE dbo.[vehicleimages] ADD image15 VARCHAR(200) NULL
--GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image16')
ALTER TABLE dbo.[vehicleimages] ADD image16 VARCHAR(200) NULL
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image17')
ALTER TABLE dbo.[vehicleimages] ADD image17 VARCHAR(200) NULL
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image18')
ALTER TABLE dbo.[vehicleimages] ADD image18 VARCHAR(200) NULL
GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image19')
--ALTER TABLE dbo.[vehicleimages] ADD image19 VARCHAR(200) NULL
--GO

--IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image20')
--ALTER TABLE dbo.[vehicleimages] ADD image20 VARCHAR(200) NULL
--GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image9')
ALTER TABLE dbo.[vehicleimages] DROP image9
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image10')
ALTER TABLE dbo.[vehicleimages] DROP image10
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image11')
ALTER TABLE dbo.[vehicleimages] DROP image11
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image12')
ALTER TABLE dbo.[vehicleimages] DROP image12
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image13')
ALTER TABLE dbo.[vehicleimages] DROP image13
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image14')
ALTER TABLE dbo.[vehicleimages] DROP image14
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image15')
ALTER TABLE dbo.[vehicleimages] DROP image15
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image16')
ALTER TABLE dbo.[vehicleimages] DROP image16
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image17')
ALTER TABLE dbo.[vehicleimages] DROP COLUMN image17
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image18')
ALTER TABLE dbo.[vehicleimages] DROP image18
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image19')
ALTER TABLE dbo.[vehicleimages] DROP image19
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'vehicleimages' AND COLUMN_NAME = 'image20')
ALTER TABLE dbo.[vehicleimages] DROP image20 
GO